# Server configuration
server:
  port: 8088
  servlet:
    context-path: /shopapp

api:
  prefix: api/v1

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  paths-to-match:             # What API paths should be included in the docs
#    - /api/v1/**
    - /**
  default-produces-media-type: application/json
  paths-to-exclude:
    - /actuator/**




management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/actuator
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    org.springframework.security: DEBUG  # Set log level for a Spring framework
    com.example.shopapp: INFO  # Example: your app's base package
  config: classpath:logback-spring.xml  # Custom logback configuration file


# Application properties
spring:
  kafka:
    listener:
      auto-startup: false
    admin:
      auto-create: false # If you are not using Kafka’s AdminClient at all, you can disable it by adding:
    bootstrap-servers: ${KAFKA_BROKER_SERVER:localhost}:${KAFKA_BROKER_PORT:9092}

    properties:
      spring.json.type.mapping: category:com.example.shopapp.models.Category,product:com.example.shopapp.models.Product

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer




  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0

  #  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 3600  # optional, seconds to cache
    # default-locale is NOT a standard spring.messages property

  application:
    name: shopapp

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp_java
    #url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    #username: ${DBMS_USERNAME}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4300/auth/google/callback}"
            authorization-grant-type: authorization_code
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}  # 👈 Use env variables here too!
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "${FACEBOOK_REDIRECT_URI:http://localhost:4300/auth/facebook/callback}"
            scope:
              - email
              - public_profile
            authorization-grant-type: authorization_code
            client-name: Facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          facebook:
            authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)



# JWT
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: LLaTGzHHnTJRbK0+yVZq3ff/H+/JRmmoK2SCMaaJ5Eo=

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}
  tmn-code: ${VNPAY_TMN_CODE}
  secret-key: ${VNPAY_SECRET_KEY}
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
