# Server configuration
server:
  port: 8088
  servlet:
    context-path: /shopapp

api:
  prefix: api/v1

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  paths-to-match:             # What API paths should be included in the docs
#    - /api/v1/**
    - /**
  default-produces-media-type: application/json
  paths-to-exclude:
    - /actuator/**




management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/actuator
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.springframework.security: DEBUG  # Set log level for a Spring framework
    com.yourcompany.yourapp: INFO  # Example: your app's base package
  config: classpath:logback-spring.xml  # Custom logback configuration file


# Application properties
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0

  #  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 3600  # optional, seconds to cache
    # default-locale is NOT a standard spring.messages property

  application:
    name: shopapp

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp_java
    #url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    #username: ${DBMS_USERNAME}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


# JWT
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: LLaTGzHHnTJRbK0+yVZq3ff/H+/JRmmoK2SCMaaJ5Eo=
