# Server configuration
server:
  port: 8088
  servlet:
    context-path: /shopapp

api:
  prefix: api/v1

# Application properties
spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 3600  # optional, seconds to cache
    # default-locale is NOT a standard spring.messages property

  application:
    name: shopapp

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp_java
    #url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    #username: ${DBMS_USERNAME}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


# JWT
jwt:
  expiration: 3600 # seconds
  refreshable-duration: 7200
  secretKey: LLaTGzHHnTJRbK0+yVZq3ff/H+/JRmmoK2SCMaaJ5Eo=
